let model = {
  id_sot_o: { val: "" },
  city_id: { val: "" },
  group_id: { val: "" },
  date_begin: { val: "" },
  base_salary: { val: "" },
  bonus: { val: "" },
}

let view = {};

let view2 = {
  Filials: [
    { "label": "Златоуст", "value2": "1" },
    { "label": "Орск", "value": "2" },
    { "label": "Челябинск", "value": "3" },
    { "label": "Миасс", "value": "6" },
    { "label": "Стерлитамак", "value": "7" },
    { "label": "Салават", "value": "9" },
    { "label": "Рудный", "value": "10" },
    { "label": "Костанай", "value": "11" },
    { "label": "Екатеринбург", "value": "13" },
    { "label": "Москва", "value": "14" },
    { "label": "Петропавловск", "value": "17" },
    { "label": "Павлодар", "value": "18" },
    { "label": "Другой город РФ", "value": "19" },
    { "label": "Другой город КЗ", "value": "20" },
    { "label": "Ижевск", "value": "21" },
    { "label": "Ишимбай", "value": "22" },
    { "label": "Уральск", "value": "24" },
    { "label": "Ташкент", "value": "25" }
  ],

  Groups: [
    { "vlaue": "9", "label": "ИТР" },
    { "vlaue": "12", "label": "С" },
    { "vlaue": "19", "label": "Фикс прайс" },
    { "vlaue": "22", "label": "Озон" },
    { "vlaue": "29", "label": "ГТ" },
    { "vlaue": "32", "label": "МТС" },
    { "vlaue": "33", "label": "Вгастроном" },
    { "vlaue": "38", "label": "ГКЗ" },
    { "vlaue": "39", "label": "СКБ" },
    { "vlaue": "44", "label": "Пятерочка" },
    { "vlaue": "51", "label": "УБРиР" },
    { "vlaue": "54", "label": "Рольф" },
    { "vlaue": "55", "label": "Dpd" },
    { "vlaue": "57", "label": "Сити-Колл" },
    { "vlaue": "62", "label": "Альфа банк ПФ" },
    { "vlaue": "63", "label": "Уралсиб" },
    { "vlaue": "67", "label": "Тинькофф" },
    { "vlaue": "73", "label": "Д" },
    { "vlaue": "74", "label": "Рольф исход" },
    { "vlaue": "76", "label": "Ночь" },
    { "vlaue": "77", "label": "Пятерочка СФ" },
    { "vlaue": "79", "label": "Детский мир" },
    { "vlaue": "83", "label": "Тикетленд" },
    { "vlaue": "84", "label": "Аарон" },
    { "vlaue": "85", "label": "Медведь " },
    { "vlaue": "86", "label": "Аарон ВП" },
    { "vlaue": "87", "label": "Гчат" },
    { "vlaue": "90", "label": "ОТТО" },
    { "vlaue": "92", "label": "ГУК" },
    { "vlaue": "94", "label": "Хедхантер" },
    { "vlaue": "95", "label": "Рольф премиум" },
    { "vlaue": "97", "label": "НСВ" },
    { "vlaue": "99", "label": "Теле 2" },
    { "vlaue": "100", "label": "Гигант" },
    { "vlaue": "105", "label": "ЦМД" },
    { "vlaue": "115", "label": "Рольф опрос" },
    { "vlaue": "117", "label": "Бургер Кинг" },
    { "vlaue": "120", "label": "Озон селлеры" },
    { "vlaue": "121", "label": "К-телеком" },
    { "vlaue": "122", "label": "Лента СФ" },
    { "vlaue": "123", "label": "Лента ПФ" },
    { "vlaue": "124", "label": "ДИТ" },
    { "vlaue": "125", "label": "МТС вход" },
    { "vlaue": "126", "label": "Газпромнефть" },
    { "vlaue": "127", "label": "ГВСП" },
    { "vlaue": "128", "label": "МТС пилот чаты" },
    { "vlaue": "129", "label": "МТС пилот голос" },
    { "vlaue": "133", "label": "Ламода B2B" },
    { "vlaue": "134", "label": "Ригла" },
    { "vlaue": "135", "label": "Протек" },
    { "vlaue": "137", "label": "Бургер Кинг Support" },
    { "vlaue": "138", "label": "МТС премиум" },
    { "vlaue": "139", "label": "Ламода чаты" },
    { "vlaue": "140", "label": "МТС Страхование" },
    { "vlaue": "141", "label": "Теле 2 исход" },
    { "vlaue": "142", "label": "Альфа банк СФ" },
    { "vlaue": "143", "label": "Детский мир ВДС" },
    { "vlaue": "144", "label": "Альфа банк Исход" },
    { "vlaue": "146", "label": "Ростелеком РСО" },
    { "vlaue": "147", "label": "МТС тендер" },
    { "vlaue": "155", "label": "Семь телеком" },
    { "vlaue": "156", "label": "Ламода первая линия" },
    { "vlaue": "157", "label": "Озон Тикет" },
    { "vlaue": "158", "label": "Х5Пакет" },
    { "vlaue": "159", "label": "СДЭК" },
    { "vlaue": "160", "label": "ВК чаты" },
    { "vlaue": "162", "label": "Ресечеры Иные РФ" },
    { "vlaue": "163", "label": "ТТС" },
    { "vlaue": "164", "label": "ТТС ТМ" },
    { "vlaue": "165", "label": "Детский мир чаты" },
    { "vlaue": "166", "label": "Магнит" },
    { "vlaue": "167", "label": "Озон 2" },
    { "vlaue": "168", "label": "РТК" },
    { "vlaue": "169", "label": "Бургер Кинг Доставка" },
    { "vlaue": "170", "label": "Пятерочка ДВ" },
    { "vlaue": "171", "label": "ВК чаты ПФ" },
    { "vlaue": "172", "label": "МТС ШПД" },
    { "vlaue": "173", "label": "Ингосстрах" },
    { "vlaue": "174", "label": "Альфа банк разовый" }
  ]

}